{
 "title": "GNS3LAB",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "R1",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bw Gi0/0",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "alias": "ifHCInOctects",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ifTable",
       "query": "SELECT mean(\"ifHCInOctets\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '172.16.50.111') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCInOctets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "172.16.50.111" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/0" }
       ]
      },
      {
       "alias": "ifHCOutOctects",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ifTable",
       "query": "SELECT mean(\"ifHCInOctets\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '172.16.50.111') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCOutOctets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "172.16.50.111" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/0" }
       ]
      }
     ]
    },
    {
     "title": "Pkts Gi0/0",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "ifHCINUcastPkts",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "ifTable",
       "query": "SELECT count(\"ifHCInUcastPkts\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '172.16.50.111') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCInUcastPkts" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "172.16.50.111" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/0" }
       ]
      },
      {
       "alias": "ifHCOutUcastPkts",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ifTable",
       "query": "SELECT mean(\"ifHCInOctets\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '172.16.50.111') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCOutUcastPkts" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "172.16.50.111" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/0" }
       ]
      }
     ]
    },
    {
     "title": "Bw Gi0/1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "alias": "ifHCInOctects",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ifTable",
       "query": "SELECT mean(\"ifHCInOctets\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '172.16.50.111') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCInOctets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "172.16.50.111" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/1" }
       ]
      },
      {
       "alias": "ifHCOutOctects",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ifTable",
       "query": "SELECT mean(\"ifHCInOctets\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '172.16.50.111') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCOutOctets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "172.16.50.111" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/1" }
       ]
      }
     ]
    },
    {
     "title": "Pkts Gi0/1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "ifHCINUcastPkts",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "ifTable",
       "query": "SELECT count(\"ifHCInUcastPkts\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '10.0.0.1') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCInUcastPkts" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "10.0.0.1" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/1" }
       ]
      },
      {
       "alias": "ifHCOutUcastPkts",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ifTable",
       "query": "SELECT mean(\"ifHCInOctets\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '172.16.50.111') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCOutUcastPkts" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "172.16.50.111" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/1" }
       ]
      }
     ]
    },
    {
     "title": "Bw Gi0/2",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "alias": "ifHCInOctects",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ifTable",
       "query": "SELECT mean(\"ifHCInOctets\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '172.16.50.111') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCInOctets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "172.16.50.111" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/2" }
       ]
      },
      {
       "alias": "ifHCOutOctects",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ifTable",
       "query": "SELECT mean(\"ifHCInOctets\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '172.16.50.111') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCOutOctets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "172.16.50.111" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/2" }
       ]
      }
     ]
    },
    {
     "title": "Pkts Gi0/2",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "ifHCINUcastPkts",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "ifTable",
       "query": "SELECT count(\"ifHCInUcastPkts\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '10.0.0.5') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCInUcastPkts" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "10.0.0.5" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/2" }
       ]
      },
      {
       "alias": "ifHCOutUcastPkts",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ifTable",
       "query": "SELECT mean(\"ifHCInOctets\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '172.16.50.111') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCOutUcastPkts" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "172.16.50.111" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/2" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "R2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bw Gi0/0",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "alias": "ifHCInOctects",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ifTable",
       "query": "SELECT mean(\"ifHCInOctets\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '172.16.50.231') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCInOctets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "172.16.50.231" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/0" }
       ]
      },
      {
       "alias": "ifHCOutOctects",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ifTable",
       "query": "SELECT mean(\"ifHCInOctets\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '172.16.50.231') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCOutOctets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "172.16.50.231" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/0" }
       ]
      }
     ]
    },
    {
     "title": "Pkts Gi0/0",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "ifHCINUcastPkts",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "ifTable",
       "query": "SELECT count(\"ifHCInUcastPkts\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '172.16.50.231') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCInUcastPkts" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "172.16.50.231" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/0" }
       ]
      },
      {
       "alias": "ifHCOutUcastPkts",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ifTable",
       "query": "SELECT mean(\"ifHCInOctets\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '172.16.50.231') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCOutUcastPkts" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "172.16.50.231" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/0" }
       ]
      }
     ]
    },
    {
     "title": "Bw Gi0/1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "alias": "ifHCInOctects",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ifTable",
       "query": "SELECT mean(\"ifHCInOctets\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '172.16.50.231') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCInOctets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "172.16.50.231" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/1" }
       ]
      },
      {
       "alias": "ifHCOutOctects",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ifTable",
       "query": "SELECT mean(\"ifHCInOctets\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '172.16.50.231') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCOutOctets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "172.16.50.231" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/1" }
       ]
      }
     ]
    },
    {
     "title": "Pkts Gi0/1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "ifHCINUcastPkts",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "ifTable",
       "query": "SELECT count(\"ifHCInUcastPkts\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '10.0.0.2') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCInUcastPkts" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "10.0.0.2" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/1" }
       ]
      },
      {
       "alias": "ifHCOutUcastPkts",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ifTable",
       "query": "SELECT mean(\"ifHCInOctets\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '172.16.50.231') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCOutUcastPkts" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "172.16.50.231" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/1" }
       ]
      }
     ]
    },
    {
     "title": "Bw Gi0/2",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "alias": "ifHCInOctects",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ifTable",
       "query": "SELECT mean(\"ifHCInOctets\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '172.16.50.231') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCInOctets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "172.16.50.231" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/2" }
       ]
      },
      {
       "alias": "ifHCOutOctects",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ifTable",
       "query": "SELECT mean(\"ifHCInOctets\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '172.16.50.231') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCOutOctets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "172.16.50.231" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/2" }
       ]
      }
     ]
    },
    {
     "title": "Pkts Gi0/2",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "ifHCINUcastPkts",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "ifTable",
       "query": "SELECT count(\"ifHCInUcastPkts\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '10.0.0.14') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCInUcastPkts" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "10.0.0.14" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/2" }
       ]
      },
      {
       "alias": "ifHCOutUcastPkts",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ifTable",
       "query": "SELECT mean(\"ifHCInOctets\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '172.16.50.231') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCOutUcastPkts" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "172.16.50.231" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/2" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "R3",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bw Gi0/0",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "alias": "ifHCInOctects",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ifTable",
       "query": "SELECT mean(\"ifHCInOctets\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '172.16.50.135') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCInOctets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "172.16.50.135" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/0" }
       ]
      },
      {
       "alias": "ifHCOutOctects",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ifTable",
       "query": "SELECT mean(\"ifHCInOctets\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '172.16.50.135') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCOutOctets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "172.16.50.135" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/0" }
       ]
      }
     ]
    },
    {
     "title": "Pkts Gi0/0",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "ifHCINUcastPkts",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "ifTable",
       "query": "SELECT count(\"ifHCInUcastPkts\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '172.16.50.135') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCInUcastPkts" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "172.16.50.135" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/0" }
       ]
      },
      {
       "alias": "ifHCOutUcastPkts",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ifTable",
       "query": "SELECT mean(\"ifHCInOctets\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '172.16.50.135') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCOutUcastPkts" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "172.16.50.135" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/0" }
       ]
      }
     ]
    },
    {
     "title": "Bw Gi0/1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "alias": "ifHCInOctects",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ifTable",
       "query": "SELECT mean(\"ifHCInOctets\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '172.16.50.135') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCInOctets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "172.16.50.135" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/1" }
       ]
      },
      {
       "alias": "ifHCOutOctects",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ifTable",
       "query": "SELECT mean(\"ifHCInOctets\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '172.16.50.135') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCOutOctets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "172.16.50.135" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/1" }
       ]
      }
     ]
    },
    {
     "title": "Pkts Gi0/1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "ifHCINUcastPkts",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "ifTable",
       "query": "SELECT count(\"ifHCInUcastPkts\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '10.0.0.9') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCInUcastPkts" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "10.0.0.9" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/1" }
       ]
      },
      {
       "alias": "ifHCOutUcastPkts",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ifTable",
       "query": "SELECT mean(\"ifHCInOctets\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '172.16.50.135') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCOutUcastPkts" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "172.16.50.135" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/1" }
       ]
      }
     ]
    },
    {
     "title": "Bw Gi0/2",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "alias": "ifHCInOctects",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ifTable",
       "query": "SELECT mean(\"ifHCInOctets\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '172.16.50.135') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCInOctets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "172.16.50.135" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/2" }
       ]
      },
      {
       "alias": "ifHCOutOctects",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ifTable",
       "query": "SELECT mean(\"ifHCInOctets\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '172.16.50.135') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCOutOctets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "172.16.50.135" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/2" }
       ]
      }
     ]
    },
    {
     "title": "Pkts Gi0/2",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "ifHCINUcastPkts",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "ifTable",
       "query": "SELECT count(\"ifHCInUcastPkts\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '10.0.0.6') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCInUcastPkts" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "10.0.0.6" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/2" }
       ]
      },
      {
       "alias": "ifHCOutUcastPkts",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ifTable",
       "query": "SELECT mean(\"ifHCInOctets\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '172.16.50.135') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCOutUcastPkts" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "172.16.50.135" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/2" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "R4",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bw Gi0/0",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "alias": "ifHCInOctects",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ifTable",
       "query": "SELECT mean(\"ifHCInOctets\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '172.16.50.125') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCInOctets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "172.16.50.125" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/0" }
       ]
      },
      {
       "alias": "ifHCOutOctects",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ifTable",
       "query": "SELECT mean(\"ifHCInOctets\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '172.16.50.125') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCOutOctets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "172.16.50.125" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/0" }
       ]
      }
     ]
    },
    {
     "title": "Pkts Gi0/0",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "ifHCINUcastPkts",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "ifTable",
       "query": "SELECT count(\"ifHCInUcastPkts\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '172.16.50.125') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCInUcastPkts" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "172.16.50.125" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/0" }
       ]
      },
      {
       "alias": "ifHCOutUcastPkts",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ifTable",
       "query": "SELECT mean(\"ifHCInOctets\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '172.16.50.125') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCOutUcastPkts" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "172.16.50.125" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/0" }
       ]
      }
     ]
    },
    {
     "title": "Bw Gi0/1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "alias": "ifHCInOctects",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ifTable",
       "query": "SELECT mean(\"ifHCInOctets\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '172.16.50.125') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCInOctets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "172.16.50.125" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/1" }
       ]
      },
      {
       "alias": "ifHCOutOctects",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ifTable",
       "query": "SELECT mean(\"ifHCInOctets\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '172.16.50.125') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCOutOctets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "172.16.50.125" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/1" }
       ]
      }
     ]
    },
    {
     "title": "Pkts Gi0/1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "ifHCINUcastPkts",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "ifTable",
       "query": "SELECT count(\"ifHCInUcastPkts\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '10.0.0.10') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCInUcastPkts" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "10.0.0.10" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/1" }
       ]
      },
      {
       "alias": "ifHCOutUcastPkts",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ifTable",
       "query": "SELECT mean(\"ifHCInOctets\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '172.16.50.125') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCOutUcastPkts" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "172.16.50.125" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/1" }
       ]
      }
     ]
    },
    {
     "title": "Bw Gi0/2",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "alias": "ifHCInOctects",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ifTable",
       "query": "SELECT mean(\"ifHCInOctets\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '172.16.50.125') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCInOctets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "172.16.50.125" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/2" }
       ]
      },
      {
       "alias": "ifHCOutOctects",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ifTable",
       "query": "SELECT mean(\"ifHCInOctets\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '172.16.50.125') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCOutOctets" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "172.16.50.125" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/2" }
       ]
      }
     ]
    },
    {
     "title": "Pkts Gi0/2",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "ifHCINUcastPkts",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "ifTable",
       "query": "SELECT count(\"ifHCInUcastPkts\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '10.0.0.13') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCInUcastPkts" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "10.0.0.13" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/2" }
       ]
      },
      {
       "alias": "ifHCOutUcastPkts",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ifTable",
       "query": "SELECT mean(\"ifHCInOctets\") FROM \"ifTable\" WHERE (\"agent_host\"::tag = '172.16.50.125') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "ifHCOutUcastPkts" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "agent_host::tag", "operator": "=", "value": "172.16.50.125" },
        { "condition": "AND", "key": "ifName::tag", "operator": "=", "value": "Gi0/2" }
       ]
      }
     ]
    }
   ]
  }
 ]
}